site_name: Customer Churn Predictor
site_description: End-to-end data science project documentation
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Setup: setup.md
  - Architecture: architecture.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
